name: Build ThunderTools on Linux

# CHANGE TO MASTER
on:
  push:
    branches: ["development/actions"]
  pull_request:
    branches: ["master"]
 
# CHANGE TO RDKCENTRAL
# CHANGE TO MASTER
jobs:
  ThunderClientLibraries:
    uses: VeithMetro/ThunderClientLibraries/.github/workflows/Build ThunderClientLibraries on Linux.yml@development/actions-tools
