name: Build ThunderTools on Linux

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
 
jobs:
  ThunderClientLibraries:
    uses: rdkcentral/ThunderNanoServices/.github/workflows/Build ThunderNanoServices on Linux.yml@master
