name: Build ThunderTools on Linux

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
 
jobs:
  ThunderClientLibraries:
    uses: rdkcentral/ThunderClientLibraries/.github/workflows/Build ThunderClientLibraries on Linux.yml@master
