name: Build ThunderTools on Linux

# CHANGE TO MASTER
on:
  push:
    branches: ["development/actions"]
  pull_request:
    branches: ["master"]
 
jobs:
  ThunderClientLibraries:
    uses: rdkcentral/ThunderClientLibraries/.github/workflows/Build ThunderClientLibraries on Linux.yml@master
